### ISSUE TITLE
[Error] Setup stuck on Setting up host's nvidia integration...

### ISSUE THREAD

**Issue by aaravrav** [89luca89/distrobox#1589]
**Describe the bug**
When using the `--nvidia` flag, `distrobox enter` hangs on `Setting up host's nvidia integration...`

**To Reproduce**
`distrobox create --name ubuntu-gp --nvidia --init --image ubuntu:latest --additional-packages "systemd libpam-systemd"`
`distrobox enter ubuntu-gp`

**Logs**
```
$ distrobox create --name ubuntu-gp --nvidia --init --image ubuntu:latest --additional-packages "systemd libpam-systemd"
Creating 'ubuntu-gp' using image ubuntu:latest	[ OK ]
Distrobox 'ubuntu-gp' successfully created.
To enter, run:

distrobox enter ubuntu-gp

$ distrobox enter ubuntu-gp
Starting container...                   	[ OK ]
Installing basic packages...            	
 [ OK ]
Setting up devpts mounts...             	[ OK ]
Setting up read-only mounts...          	[ OK ]
Setting up read-write mounts...         	[ OK ]
Setting up host's sockets integration...	[ OK ]
Setting up host's nvidia integration... 	
```

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?: Podman
 - Which version or podman, docker or lilipod?: `5.2.3`
 - Which version of distrobox?: `1.8.0`
 - Which host distribution?: `Arch Linux`
 - How did you install distrobox? : `paru -S distrobox-git`

**Comment by 89luca89** [comment]
Hi @aaravrav can you run a `podman logs -f ubuntu-gp` and post the logs?
This way I can see where it's failing
Thanks!

**Comment by aaravrav** [comment]
@89luca89 Didn't know about that. Seems like the problem is happening due to systemd: https://0x0.st/XIiB.txt

**Comment by aaravrav** [comment]
@89luca89 Hi, any updates?

**Comment by SteavenGamerYT** [comment]
any updates?

**Comment by aaravrav** [comment]
@89luca89 any updates?

**Comment by HunterNN** [comment]
Having the same problem even without the additional packages.
[Podman Logs](https://github.com/user-attachments/files/18306288/ubuntu-gp.zip)

- Are you using podman, docker or lilipod?: Podman
- Which version or podman, docker or lilipod?: 5.3.1
- Which version of distrobox?: 1.8.0
- Which host distribution?: Bazzite
- How did you install distrobox? : Pre installed by distro

**Comment by KShivum** [comment]
I'm getting the same thing as well. Constantly restarting it seems to make it go maybe a step or two at a time. But it basically always freezes on the "Setting up host's nvidia integration" step

**Comment by 89luca89** [comment]
@KShivum do you have logs? From @HunterNN and @aaravrav logs I don't see any strange "loop" or reasons for it to take too long, except for the fact that it's a lot of files basically

**Comment by 89luca89** [comment]
> [@89luca89](https://github.com/89luca89)
> 
> > except for the fact that it's a lot of files basically
> 
> In the logs `systemd-resolved.service: Failed with result 'exit-code'.` repeats about 8000 times until I stop distrobox, wouldn't that be the issue?

But also @HunterNN has this similar issue without the systemd stuff

Anyway I also added this commit 8f19280615e4cafbaa9c83f47f82014da343bf97 for a timeout in case systemd is stuck
Can you please try again with the latest commit from git?

**Comment by DiegoGor03** [comment]
I have the same problem, no matter which image I use it freezes on nvidia integration. Installed with "curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh" on LMDE6. I tried a few minutes by updating to the latest version and it's the same. Thanks in advance.

[1.8.0logs.txt](https://github.com/user-attachments/files/18469588/1.8.0logs.txt)

**Comment by KShivum** [comment]
> [@KShivum](https://github.com/KShivum) do you have logs? From [@HunterNN](https://github.com/HunterNN) and [@aaravrav](https://github.com/aaravrav) logs I don't see any strange "loop" or reasons for it to take too long, except for the fact that it's a lot of files basically

[log.txt](https://github.com/user-attachments/files/18470281/log.txt)
I let it sit for an hour, but it is basically the same thing, it gets to that last line within 10 seconds, then doesn't move at all.

**Comment by 89luca89** [comment]
> > [@KShivum](https://github.com/KShivum) do you have logs? From [@HunterNN](https://github.com/HunterNN) and [@aaravrav](https://github.com/aaravrav) logs I don't see any strange "loop" or reasons for it to take too long, except for the fact that it's a lot of files basically
> 
> [log.txt](https://github.com/user-attachments/files/18470281/log.txt) I let it sit for an hour, but it is basically the same thing, it gets to that last line within 10 seconds, then doesn't move at all. However, if I stop it, delete the distrobox container with distrobox rm and try it again, it'll make it farther before freezing and eventually after doing it enough times it'll make it, but it can be upwards of 20-30 times

From this log I see the first time it went ok, then the following 2 times it hanged right?

**Comment by KShivum** [comment]
Yeah that was a container that I kept recreating for it to eventually work I think

**Comment by 89luca89** [comment]
Pushed commit 83973396d16942fde780b6ffb50161cf779fd021 which reworks the file management a bit, avoiding mounting directories and symlinks thus avoiding possible loops

this should improve possible corner cases where the mounting can get hairy

can any of you test this commit and let me know if the situation is improved?
thanks!

**Comment by KShivum** [comment]
I uninstalled and reinstalled with the latest branch install command and I'm still getting the same issue

**Comment by 89luca89** [comment]
> I uninstalled and reinstalled with the latest branch install command and I'm still getting the same issue

you need to use the `--next` flag if you use the installer, or it will always install the latest release, not the latest commit

**Comment by DiegoGor03** [comment]
I tested the latest commit and it works perfectly

**Comment by 89luca89** [comment]
it's now in release 1.8.1.1 let me know if this seals the deal 👍

**Comment by aaravrav** [comment]
@89luca89 It's now stuck on `Firing up init system...` with the same `[FAILED] Failed to start systemd-resolved.service - Network Name Resolution.` error I was getting earlier.

**Comment by 89luca89** [comment]
This seems unrelated to nvidia, so I'd say let's open a new issue to track that 👍 

The nvidia issue is solved

**Comment by 89luca89** [comment]
The systemd issue is resolved as well in this commit: 3115ccd4e906aae3288c3fbe32686270fd9ec50f

As a workaround until next release use `--init-hooks "systemctl mask systemd-resolved"`

**Comment by aaravrav** [comment]
Im using the latest commit however it dosen't work. However, `--init-hooks "systemctl mask systemd-resolved"` works fine.

**Comment by shayaknyc** [comment]
Hey folks, came here because I was experiencing a similar issue but my `podman log` did not indicate the issue was with `systemd`. That said, I did follow a suggestion from [this issue ](https://github.com/zelikos/davincibox/issues/151) to replace `--nvidia` with `--additional-flags "--gpus all"` which created the distrobox container just fine, however, when attempting to enter the distrobox this is the error I received:
```
Error: unable to start container "d9172facc4dc2f84d25a0338c076dd85a998d307f6615d112632fa11a7decab2": setting up CDI devices: failed to inject devices: failed to stat CDI host device "/dev/dri/card0": no such file or directory
```
FWIW, I'm using the latest Nvidia driver and CUDA:
```
$ nvidia-smi
Wed Aug 20 14:41:37 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.76.05              Driver Version: 580.76.05      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 Ti     Off |   00000000:01:00.0  On |                  N/A |
| 53%   44C    P2             47W /  200W |    1212MiB /   8192MiB |      4%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

Any ideas?

**Comment by MalikKillian** [comment]
This issue actually still persists for me (Linux 6.15.9-103.bazzite.fc42.x86_64) on distrobox `1.8.1.2`.

Using this file:
```
[fedora-toolbox-41]
init_hooks=systemctl mask systemd-resolved
image=quay.io/fedora/fedora-toolbox:41
init=false
start_now=true
nvidia=true
pull=true
root=false
replace=true
```

The output hangs at "Setting up host's nvidia integration...".

Adding this to the file:
```
pre_init_hooks=sleep 30
```

It usually works. Maybe 1 out of 10 times I've seen it still hang.

**Comment by trevor-the-developer** [comment]
I had this issue today and I suspect its due to having a few containers with the `--nvidia` flag enabled when they were created.  I had to shutdown the containers and then the problematic container worked fine got past the nvidia integration message.

My system spec is:
```
bazzite-gnome-nvidia:stable 
Bazzite
Linux 6.17.7-ba25.fc43.x86_64
55 mins

Precision 5550
Intel(R) Core(TM) i9-10885H (16) @ 5.30 GHz
NVIDIA Quadro T2000 Mobile / Max-Q [Discrete]
Intel UHD Graphics @ 1.25 GHz [Integrated]
9.21 GiB / 62.53 GiB (15%)
459.99 GiB / 475.35 GiB (97%) - btrfs
1920x1200 in 16", 60 Hz [Built-in] *
1080x1920 @ 1.78x in 23", 60 Hz [External]
100% [AC Connected]

GNOME 49.1
Mutter (Wayland)
bash 5.3.0
Ptyxis 49.2
2569 (rpm), 126 (flatpak), 1 (brew-cask)

```
