### ISSUE TITLE
[Error] Problem setting up user in container.

### ISSUE THREAD

**Issue by baduhai** [89luca89/distrobox#168]
**Describe the bug**
Trying to follow the running [latest gnome guide](https://github.com/89luca89/distrobox/blob/main/docs/posts/run_latest_gnome_kde_on_distrobox.md#running-latest-gnome), and user setup in the container fails.

**To Reproduce**
1. `distrobox create --name fedora --image registry.fedoraproject.org/fedora:latest`
2. `distrobox-enter --name fedora`
```
2022-02-13T11:24:58.948964497Z Warning: there was a problem setting up the user
2022-02-13T11:25:00.872632518Z Changing password for user user.
2022-02-13T11:25:00.873485165Z Error: An error occurred
```

**Expected behavior**
User setup succeeds.

**Logs**
Skipped to relevant section:
```
+ printf 'Defaults !fqdn\n'
+ grep -q 'user ALL = (root) NOPASSWD:ALL' /etc/sudoers.d/sudoers
+ printf '%s ALL = (root) NOPASSWD:ALL\n' user
+ grep -q user /etc/group
+ grep -q user /etc/passwd
+ useradd --home-dir /home/user --no-create-home --shell /bin/bash --uid 1000 --gid 1000 user
useradd: user 'user' already exists
+ printf 'Warning: there was a problem setting up the user\n'
Warning: there was a problem setting up the user
++ cat /proc/sys/kernel/random/uuid
+ temporary_password=8fbbcb57-b9aa-4aeb-a5de-4f7d4f0c6979
+ printf '%s\n%s\n' 8fbbcb57-b9aa-4aeb-a5de-4f7d4f0c6979 8fbbcb57-b9aa-4aeb-a5de-4f7d4f0c6979
+ passwd user
passwd: Authentication token manipulation error
Changing password for user user.
+ '[' 1 -ne 0 ']'
Error: An error occurred
+ printf 'Error: An error occurred\n'
```

**Desktop (please complete the following information):**
 - OS: OpenSUSE Tumbleweed
 - Version: Latest snapshot (20220210)

**Comment by 89luca89** [comment]
Hi @baduhai 
What version of distrobox are you using?

Can you try the latest version from git? Probably it is related to a bug fixed in https://github.com/89luca89/distrobox/commit/6186c105654f07179fbf5e942c32cac99b2b3c62

**Comment by 89luca89** [comment]
@baduhai Version 1.2.13 is out and it includes the fix that should resolve this, let me know if it works :+1:

**Comment by 89luca89** [comment]
@baduhai any news on this?

**Comment by baduhai** [comment]
Sorry it took so long to reply, I haven't yet received the update on tumbleweed, I'll try compiling from source.

**Comment by onny** [comment]
Hey, I still get this error

```
distrobox create -n debian --image arm64v8/debian --root
distrobox enter --root debian
[...]
Container Setup Complete!
[sudo] password for onny: 
You need to install grc!
⚠️  First time user password setup ⚠️ 
Changing password for onny.
Current password: 
passwd: Authentication token manipulation error
passwd: password unchanged
```
I'm unable to use root on the container and sudo doesn't work too :(
```
sudo apt install flutter
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```

**Comment by IlgazC** [comment]
I just tried on a current openSUSE Tumbleweed, making sure I have the git version ('which distrobox') , unfortunately the bug is still there. Is there any way to have full debug log attached?
