### ISSUE TITLE
[Suggestion] Implement desktop icons integration

### ISSUE THREAD

**Issue by Meister1593** [89luca89/distrobox#266]
**Is your feature request related to a problem? Please describe.**
Every app that is now exported would not have icon, and thus it will be inconsistent with other desktop apps

**Describe the solution you'd like**
distrobox-export should handle icons being available to outside DE, either by copying png files or by symlinking them

**Additional context**
Some apps (like Webex) use custom path for icon from inside container that cannot be resolved outside
```desktop
[Desktop Entry]
Version=42.5.0.22187
Name=Webex  (on fedora-36)
Comment=Webex
Exec=/home/plyshka/.local/bin/distrobox-enter -n fedora-36 -- '  /opt/Webex/bin/CiscoCollabHost  %U'
 Icon=/opt/Webex/bin/sparklogosmall.png
Terminal=false
Type=Application
Categories=Utility;Application;
MimeType=x-scheme-handler/webexteams
StartupWMClass=webex
```
Or some apps (like steam) don't even use paths and straight use name for icon (it also can be a different name, steam flatpak for example takes icon from place like this: `/home/plyshka/.local/share/flatpak/exports/share/icons/hicolor/16x16/apps/com.valvesoftware.Steam.png`)
```desktop
[Desktop Entry]
Name=Steam (Runtime)  (on arch)
Comment=Application for managing and playing games on Steam
Comment[pt_BR]=Aplicativo para jogar e gerenciar jogos no Steam
...
...
Comment[vi]=Ứng dụng để quản lý và chơi trò chơi trên Steam
Exec=/usr/bin/distrobox-enter -T -n arch -- "  /usr/bin/steam-runtime  %U"
 Icon=steam
Terminal=false
Type=Application
Categories=Network;FileTransfer;Game;
MimeType=x-scheme-handler/steam;x-scheme-handler/steamlink;
Actions=Store;Community;Library;Servers;Screenshots;News;Settings;BigPicture;Friends;
PrefersNonDefaultGPU=true
X-KDE-RunOnDiscreteGpu=true
```

**Comment by 89luca89** [comment]
Tested steam, webex and other programs, now they export the icon correctly :+1:

**Comment by Meister1593** [comment]
> Tested steam, webex and other programs, now they export the icon correctly +1

I just tested and webex did work, but steam is still just `Icon=steam` in desktop file

**Comment by Meister1593** [comment]
> > > Tested steam, webex and other programs, now they export the icon correctly +1
> > 
> > 
> > I just tested and webex did work, but steam is still just `Icon=steam` in desktop file
> 
> Yep should be ok, as it copies the icon in ~/.local/share/icons and should be picked, worked for me on steam and other apps

it looks like this for me
![image](https://user-images.githubusercontent.com/7141787/170729040-9f9015c6-5299-43a3-9868-2167ed647c37.png)
and i don't have steam icon in `~/.local/share/icons` (~ being my user outside of container)

**Comment by Meister1593** [comment]
> I just used steam from fedora's rpmfusion, how di you install it? I see arch, is it from AUR? If you give me some info I'll test your setup

Regular steam from multilib repository
![image](https://user-images.githubusercontent.com/7141787/170731121-5b4415db-1f0f-48b2-b39c-6119074a20a7.png)

**Comment by 89luca89** [comment]
That's really strange, using latest `main` commits:

![image](https://user-images.githubusercontent.com/598882/170738146-ca43b559-9517-44e9-b648-4be98ca02e3c.png)
![image](https://user-images.githubusercontent.com/598882/170738173-2c0550f8-c518-42db-91c1-a019fd59cc88.png)

**Comment by Meister1593** [comment]
> That's really strange, using latest `main` commits:
> 
> ![image](https://user-images.githubusercontent.com/598882/170738146-ca43b559-9517-44e9-b648-4be98ca02e3c.png) ![image](https://user-images.githubusercontent.com/598882/170738173-2c0550f8-c518-42db-91c1-a019fd59cc88.png)

i noticed that i have such errors often, is this normal?
![image](https://user-images.githubusercontent.com/7141787/170741807-23a5ec63-e017-4e53-a9bf-ef77f0188cba.png)

**Comment by Meister1593** [comment]
Ah, i exported steam-runtime instead of steam, that was the problem

**Comment by Meister1593** [comment]
Exporting just `steam` works fine, yes
This is a bit off-topic, but i'm still worried that i have some errors during normal usage of package manager... i think that happened with other containers too
![image](https://user-images.githubusercontent.com/7141787/170742514-f40c4e07-b75b-4052-849c-88f29353d7c5.png)
(this was just an update)

**Comment by Meister1593** [comment]
Ok it might be SELinux issue altogether (i'm on fedora)

But now i think i found something that doesn't actually export icon and it might be a bug
`CKAN` for ksp, installed through AUR that has this contents in:
`/usr/share/applications/ckan.desktop`
```desktop
[Desktop Entry]
Name=CKAN
Comment=Comprehensive Kerbal Archive Network client
Icon=/usr/share/icons/ckan.ico
Categories=Game;Utility
Exec=/usr/bin/ckan
StartupNotify=true
Terminal=false
Type=Application
Version=1.0
```
results in exported 
`/home/plyshka/.local/share/applications/arch-ckan.desktop`:
```desktop
[Desktop Entry]
Name=CKAN  (on arch)
Comment=Comprehensive Kerbal Archive Network client
Icon=/usr/share/icons/ckan.ico
Categories=Game;Utility
Exec=/home/plyshka/.local/bin/distrobox-enter -n arch -- "  /usr/bin/ckan"
StartupNotify=true
Terminal=false
Type=Application
Version=1.0
StartupWMClass=ckan
```
which has wrong path to icon `/usr/share/icons/ckan.ico`
but actual icon is there `/home/plyshka/.local/share/icons/ckan.ico`

**Comment by 89luca89** [comment]
Interesting case, I'll reopen the issue so I can investigate and fix thanks @Meister1593 

Also about the errors, they are fixed in main 1.2.16 version :+1:

**Comment by Meister1593** [comment]
> 

i'm on main branch, just pulled new changes
do i need to re-create container... or can i update existing ones?

**Comment by 89luca89** [comment]
> > 
> 
> i'm on main branch, just pulled new changes do i need to re-create container... or can i update existing ones?

Just stop it, and start it again for changes to take effect

**Comment by 89luca89** [comment]
@Meister1593 with latest commit it works also for hardcoded paths in Icon= 
Can you test? I've tested with `ckan-bin` as you suggested and now works

**Comment by Meister1593** [comment]
> 

just tried and it's still the same system path in exported desktop file `Icon=/usr/share/icons/ckan.ico`

**Comment by 89luca89** [comment]
did you restart the container after updating?

**Comment by Meister1593** [comment]
Ok hold on a second, i might have incorrectly used install distrobox with script (without --prefix)

**Comment by Meister1593** [comment]
> did you restart the container after updating?
Nope, still the same thing, restarted container too

**Comment by 89luca89** [comment]
Check if `distrobox-export` is correctly updated (eg you created the container with `distrobox-export` in /usr/bin and now you installed in /usr/local/bin) 

The container inside binds the `distrobox-export` from the host, in the moment of creation, so if it's `/usr/bin` and you now installed everything in `/usr/local/bin`, then it won't match

you can call from inside the container directly with: `/run/host/usr/local/bin/distrobox-export` for this test
Or easier, if you installed in ~/.local/bin, just use that 

As you can see here, the last commit generates the Icon= correctly:

![image](https://user-images.githubusercontent.com/598882/170762367-c9a4d3fe-17fa-41a1-bad2-13131f31cea7.png)

**Comment by Meister1593** [comment]
> can you verify that the `distrobox-export` in the container matches the one that is on git?

weird... the one inside repository is new, but in `~/.local/bin` is not

**Comment by 89luca89** [comment]
> > can you verify that the `distrobox-export` in the container matches the one that is on git?
> 
> weird... the one inside repository is new, but in `~/.local/bin` is not

You need to `git clone` or download the sources
`install` will just grab the latest **release**, not the latest commit

**Comment by Meister1593** [comment]
> > > can you verify that the `distrobox-export` in the container matches the one that is on git?
> > 
> > 
> > weird... the one inside repository is new, but in `~/.local/bin` is not
> 
> You need to `git clone` or download the sources `install` will just grab the latest **release**, not the latest commit

yep i'm doing that inside git repository, it should use files from the repository with it right?

**Comment by Meister1593** [comment]
that's... weird? (tmp file is from github)
![image](https://user-images.githubusercontent.com/7141787/170763544-ebaa2395-1e3d-477d-95c1-9046fc3d9d72.png)

**Comment by Meister1593** [comment]
nevermind, i'm just looked at specific commit version
it matches up with github perfectly fine

**Comment by Meister1593** [comment]
this is what inside the arch container, no matter what i do
![image](https://user-images.githubusercontent.com/7141787/170764093-811cf2fe-7bbb-486e-9b79-6b05e83c6980.png)

**Comment by Meister1593** [comment]
this doesn't seem right
how did this happen?
![image](https://user-images.githubusercontent.com/7141787/170764264-220e7265-ff33-4993-b98c-f1ee0dd0809e.png)

**Comment by Meister1593** [comment]
it seems like an intentional behaviour (mounting distrobox-export to this location), but at this point it almost looks like it copied over to the container

**Comment by 89luca89** [comment]
No it's not intended
As you can see here, the intended path should be `/usr/bin/distrobox-export` https://github.com/89luca89/distrobox/blob/a911d6320ae57c29a50d00d8c2b641d7be50889f/distrobox-create#L428

Probably you installed distrobox inside the container
I suggest to use a new container to make sure

**Comment by Meister1593** [comment]
> No it's not intended As you can see here, the intended path should be `/usr/bin/distrobox-export`
> 
> https://github.com/89luca89/distrobox/blob/a911d6320ae57c29a50d00d8c2b641d7be50889f/distrobox-create#L428
> 
> Probably you installed distrobox inside the container I suggest to use a new container to make sure

yup, new arch container properly exports ckan with icon

**Comment by 89luca89** [comment]
Cool, closing this then 👍
