### ISSUE TITLE
[Error] failed to bind mount on ArchLinux container

### ISSUE THREAD

**Issue by tyhawk** [89luca89/distrobox#778]
**Describe the bug**
When starting a ArchLinux container, certain volumes fail to mount.
```
Setting up read-write mounts...        
 Warning: failed to bind mount /run/host/mnt to /mnt
 Warning: Cannot bind mount /mnt to /run/host/mnt
 Warning: failed to bind mount /run/host/mnt to /mnt
 Warning: Cannot bind mount /mnt to /run/host/mnt [ OK ]
 Setting up host's sockets integration...        [ OK ]
 Integrating host's themes, icons, fonts...
 Warning: failed to bind mount /run/host/usr/share/themes to /usr/local/share/themes
 Warning: Cannot bind mount /run/host/usr/share/themes to /usr/local/share/themes
 Warning: Themes integration with the host is disabled.
 Warning: failed to bind mount /run/host/usr/share/icons to /usr/local/share/icons
 Warning: Cannot bind mount /run/host/usr/share/icons to /usr/local/share/icons
 Warning: Icons integration with the host is disabled.
 Warning: failed to bind mount /run/host/usr/share/fonts to /usr/local/share/fonts
 Warning: Cannot bind mount /run/host/usr/share/fonts to /usr/local/share/fonts
 Warning: Fonts integration with the host is disabled. [ OK ]
 Setting up package manager exceptions...        [ OK ]
 Setting up pacman exceptions...                 [ OK ]
 Integrating host's themes, icons, fonts...
 Warning: failed to bind mount /run/host/usr/share/themes to /usr/local/share/themes
 Warning: Cannot bind mount /run/host/usr/share/themes to /usr/local/share/themes
 Warning: Themes integration with the host is disabled.
 Warning: failed to bind mount /run/host/usr/share/icons to /usr/local/share/icons
 Warning: Cannot bind mount /run/host/usr/share/icons to /usr/local/share/icons
 Warning: Icons integration with the host is disabled.
 Warning: failed to bind mount /run/host/usr/share/fonts to /usr/local/share/fonts
 Warning: Cannot bind mount /run/host/usr/share/fonts to /usr/local/share/fonts
 Warning: Fonts integration with the host is disabled. [ OK ]
```

**To Reproduce**
Even when creating a new container, the errors occur, but only if it is an ArchLinux container.
```
> distrobox create --pull --image archlinux archdev
```
However, when I create a container based on another flavour, it works without the bind mount errors.
```
> distrobox create --pull --image ubuntu:22.04 ubuntu

> distrobox enter ubuntu
Container ubuntu is not running.
Starting container ubuntu
run this command to follow along:

 podman logs -f ubuntu

 Starting container...                           [ OK ]
 Installing basic packages...                    [ OK ]
 Setting up read-only mounts...                  [ OK ]
 Setting up read-write mounts...                 [ OK ]
 Setting up host's sockets integration...        [ OK ]
 Integrating host's themes, icons, fonts...      [ OK ]
 Setting up package manager exceptions...        [ OK ]
 Setting up dpkg exceptions...                   [ OK ]
 Setting up apt hooks...                         [ OK ]
 Setting up sudo...                              [ OK ]
 Setting up package manager exceptions...        [ OK ]
 Setting up dpkg exceptions...                   [ OK ]
 Setting up apt hooks...                         [ OK ]
 Setting up sudo...                              [ OK ]
 Setting up groups...                            [ OK ]
 Setting up users...                             [ OK ]
 Setting up groups...                            [ OK ]
 Setting up users...                             [ OK ]
 Executing init hooks...                         [ OK ]

Container Setup Complete!
```
Inside the container, /mnt is mounted.
```
> ls -lah /mnt
total 48K
dr-xr-xr-x.  1 nobody   nogroup   180 Mar 29 17:20 .
dr-xr-xr-x.  1 root     root       32 Jun  1 16:47 ..
drwxrwxrwx. 24 nobody   nogroup  4.0K May 19 14:34 backup
drwxrwxrwx.  3 nobody   nogroup  4.0K Jun  1 16:38 cache
drwxrwxrwx. 19 nobody   nogroup  4.0K May 30 23:33 fotos
drwxrwxrwx.  8 nobody   nogroup  4.0K May 16 09:25 homevideos
drwxrwxrwx.  7 nobody   nogroup  4.0K Sep  6  2022 iso
drwxr-xr-x.  1 nobody   nogroup   428 Sep 22  2022 projects
```

**Expected behavior**
This problem only started to occur since a few days and only with ArchLinux containers, so I am assuming it's an Arch-specific problem with a package that got an update in the last week or so.

**Logs**
```
distrobox: Integrating host's themes, icons, fonts...
+ mount_bind /run/host/usr/share/themes /usr/local/share/themes rw
+ source_dir=/run/host/usr/share/themes
+ target_dir=/usr/local/share/themes
+ mount_flags=rw
+ '[' -d /run/host/usr/share/themes ']'
+ '[' -e /usr/local/share/themes ']'
+ findmnt /usr/local/share/themes
+ '[' -d /run/host/usr/share/themes ']'
+ mkdir -p /usr/local/share/themes
+ '[' rw = '' ']'
+ mount --rbind -o rw /run/host/usr/share/themes /usr/local/share/themes
mount: /usr/local/share/themes: permission denied.
       dmesg(1) may have more information after failed mount system call.
+ printf 'Warning: failed to bind mount %s to %s\n' /run/host/usr/share/themes /usr/local/share/themes
Warning: failed to bind mount /run/host/usr/share/themes to /usr/local/share/themes
+ return 1
+ printf 'Warning: Cannot bind mount /run/host/usr/share/themes to /usr/local/share/themes\n'
Warning: Cannot bind mount /run/host/usr/share/themes to /usr/local/share/themes
Warning: Themes integration with the host is disabled.
+ printf 'Warning: Themes integration with the host is disabled.\n'
+ mount_bind /run/host/usr/share/icons /usr/local/share/icons rw
+ source_dir=/run/host/usr/share/icons
+ target_dir=/usr/local/share/icons
+ mount_flags=rw
+ '[' -d /run/host/usr/share/icons ']'
+ '[' -e /usr/local/share/icons ']'
+ findmnt /usr/local/share/icons
+ '[' -d /run/host/usr/share/icons ']'
+ mkdir -p /usr/local/share/icons
+ '[' rw = '' ']'
+ mount --rbind -o rw /run/host/usr/share/icons /usr/local/share/icons
mount: /usr/local/share/icons: permission denied.
       dmesg(1) may have more information after failed mount system call.
+ printf 'Warning: failed to bind mount %s to %s\n' /run/host/usr/share/icons /usr/local/share/icons
Warning: failed to bind mount /run/host/usr/share/icons to /usr/local/share/icons
+ return 1
Warning: Cannot bind mount /run/host/usr/share/icons to /usr/local/share/icons
+ printf 'Warning: Cannot bind mount /run/host/usr/share/icons to /usr/local/share/icons\n'
+ printf 'Warning: Icons integration with the host is disabled.\n'
Warning: Icons integration with the host is disabled.
+ mount_bind /run/host/usr/share/fonts /usr/local/share/fonts rw
+ source_dir=/run/host/usr/share/fonts
+ target_dir=/usr/local/share/fonts
+ mount_flags=rw
+ '[' -d /run/host/usr/share/fonts ']'
+ '[' -e /usr/local/share/fonts ']'
+ findmnt /usr/local/share/fonts
+ '[' -d /run/host/usr/share/fonts ']'
+ mkdir -p /usr/local/share/fonts
+ '[' rw = '' ']'
+ mount --rbind -o rw /run/host/usr/share/fonts /usr/local/share/fonts
mount: /usr/local/share/fonts: permission denied.
       dmesg(1) may have more information after failed mount system call.
+ printf 'Warning: failed to bind mount %s to %s\n' /run/host/usr/share/fonts /usr/local/share/fonts
Warning: failed to bind mount /run/host/usr/share/fonts to /usr/local/share/fonts
+ return 1
+ printf 'Warning: Cannot bind mount /run/host/usr/share/fonts to /usr/local/share/fonts\n'
Warning: Cannot bind mount /run/host/usr/share/fonts to /usr/local/share/fonts
Warning: Fonts integration with the host is disabled.
```
I do notice a `mount: /bla/bla/bla: permission denied` warning where the bind mount fails.

**Desktop (please complete the following information):**
- podman version 4.5.0
- distrobox version: 1.4.2.1
- Base OS: MicroOS based on openSUSE Tumbleweed (current version)

**Comment by ejuarezg** [comment]
I also started seeing these errors yesterday.

**Comment by 89luca89** [comment]
Hi @ejuarezg 
I;ve just tested and seems to work correctly

probably was something related to the arch image in that period span
try to pull a new image and try again

thanks

**Comment by outphase** [comment]
I am getting the same behavior after deleting and re-pulling the archlinux:latest image from docker.io. My archlinux container is not bind mounting fonts, images or themes similar to the OP.

- podman version 4.5.1
- distrobox version 1.4.2.1
- Host OS: Fedora Kinoite [uBlue-custom](https://github.com/bsherman/ublue-custom)

**Comment by 89luca89** [comment]
Hi @outphase can you try with the latest version from git? I think the issue has already been solved by another commit

**Comment by tyhawk** [comment]
I will also retest and report back ASAP.

**Comment by outphase** [comment]
I ran `git clone ...` and ran the scripts as they were to create a new `archlinux:latest` box.

It appears to work now with all `[OK]`s down the line. I can also run `distrobox enter box` with my preinstalled distrobox and still get it going.

Thanks!

**Comment by 89luca89** [comment]
This has just been fixed :+1:

**Comment by tyhawk** [comment]
In that case... looking forward to the next release? :-)

**Comment by outphase** [comment]
I confirm that this has been fixed all around for me

**Comment by abuturabofficial** [comment]
Getting the same error, even when pulling the new image:
https://pastebin.com/iC3GNWLL
